### ISSUE TITLE
move to pd-externals?

### ISSUE THREAD

**Issue by umlaeute** [pd-externals/xeq#2]
i'd like to move this repository to the @pd-externals group (to keep the "pure-data" group centered about the core components of Pd)

**Comment by danomatika** [comment]
Actually, judging from the reaction on the pd-list, the [xeq] sources are dead. I uploaded them here to see if anyone wanted to work on it and it seems the answer is no, so maybe we just remove this instead of moving it.

**Comment by danomatika** [comment]
Ping @electrickery

**Comment by electrickery** [comment]
The problem with the latest version of [xeq] is that the source is incomplete and the documentation is of a previous version. So I see no way to fill the gap. The midi-file read/write function is somewhat working, but the rest isn't.

**Comment by umlaeute** [comment]
i think @pd-externals is a better place for "dead" (and potentially resurrectable) projects than @pure-data 
I'd like to have @pd-externals to be the place where all the externals could go that don't have a dedicated team/owner (who wants to host it under their own namespace/project/server) but which can benefit from a public git repository that can accept pull requests.

**Comment by danomatika** [comment]
Sure. Go ahead and move it then, with maybe a caveat that it needs some work.

I wish there was a way for the pure-data group to have an "externals" subgroup.

**Comment by umlaeute** [comment]
moved.
